# Generated by Django 4.0.4 on 2022-05-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to='posts/img/'),
        ),
    ]
